#!/usr/bin/env php

<?php

// docker-compose run cli php console arg1=value01 arg2=value02

if ($argc == 1) echo "Welcome to console" ."\n". "Usage console command help: php console --help|-h". "\n";

$command_help = function($params) {
	foreach ($params as $key => $value) {
		if ($value == "--help" || $value == "-h") {
			return true;
		}
	}

	return false;
};

$input = function($params, $number_params) {
	$arr = [];

	for ($i = 1; $i < $number_params; $i++) { 
		$parsed = explode('=', $params[$i]);
		$arr[$parsed[0]] = $parsed[1];
	}
	return $arr;
};

if ($command_help($argv)) {
	echo "list all commands console \n";
}

?>