version: "3.4"

services:
  cli:
    container_name: php-cli
    command: "composer update"
    build:
      context: .
      target: cli
    volumes:
      - ./:/app

  app:
    container_name: php-app
    build: .
    ports:
      - 8080:80
    volumes:
      - ./:/app